# Generated by Django 4.2 on 2023-04-19 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=255, verbose_name='Título')),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('content_post', models.TextField(verbose_name='Conteúdo')),
                ('summary_post', models.TextField(verbose_name='Excerto')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('publisher_post', models.BooleanField(default=False, verbose_name='Publicado')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comment', models.CharField(max_length=150, verbose_name='Nome')),
                ('email_comment', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('date_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher_comment', models.BooleanField(default=False)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
