# Generated by Django 4.2 on 2023-04-18 15:03

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=stdimage.models.StdImageField(
                default=1,
                force_min_size=False,
                upload_to="static/images",
                variations={"thumbnail": {"crop": True, "height": 100, "width": 100}},
            ),
            preserve_default=False,
        ),
    ]
