# Generated by Django 4.2 on 2023-04-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary_post',
            field=models.TextField(verbose_name='Resumo'),
        ),
    ]
