# Generated by Django 4.2 on 2023-04-18 19:20

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to="static/images",
                variations={"thumbnail": {"crop": True, "height": 100, "width": 100}},
                verbose_name="Imagem Capa",
            ),
        ),
    ]
