# Generated by Django 4.2 on 2023-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emphasis_post',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
