# Generated by Django 4.2 on 2023-05-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_categoria_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='image_category',
            new_name='image_cat',
        ),
    ]
