# Generated by Django 4.2 on 2023-05-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
