# Generated by Django 4.2.1 on 2023-05-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_banners_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
