# Generated by Django 4.2.1 on 2023-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary_post',
            field=models.TextField(max_length=90, verbose_name='Resumo'),
        ),
    ]
