# Generated by Django 4.2.1 on 2023-05-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_summary_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='email_comment',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='user_comment',
        ),
    ]
