# Generated by Django 4.2.1 on 2023-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_comentario_email_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='status',
            field=models.CharField(choices=[('Lido', 'Lido'), ('Não Lido', 'Não Lido')], default='Não Lido', max_length=10),
        ),
    ]
