# Generated by Django 4.2.1 on 2023-05-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comentario_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='name_comment',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='post_comment',
            new_name='post',
        ),
    ]
