# Generated by Django 4.2.1 on 2023-06-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_name_comment_comentario_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publisher_comment',
        ),
    ]
